server:
  port: 9090
spring:
  datasource:
    username: root
    password: Swaraj@123
    url: jdbc:mysql://localhost:3306/advjava
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true